# Generated by Django 6.0.5 on 2026-05-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RollingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Locomotive'), ('C', 'Coach'), ('V', 'Freight car')], max_length=1)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('era', models.CharField(blank=True, max_length=5)),
                ('dcc_address', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acquired', models.CharField(blank=True, max_length=7)),
                ('prototype', models.CharField(blank=True, max_length=200)),
                ('product_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.brand')),
            ],
            options={
                'verbose_name': 'Rolling Stock',
                'verbose_name_plural': 'Rolling Stock',
                'ordering': ['type', 'brand', 'code'],
            },
        ),
    ]
